### ISSUE TITLE
Advance Warning Sign Recommendations

### ISSUE THREAD

**Issue by amsignal** [DenverConnectedVehicle/ConnectedPedestrian#7]
[AM Signal Response Advance Warning Signs.pdf](https://github.com/DenverConnectedVehicle/ConnectedPedestrian/files/3535742/AM.Signal.Response.Advance.Warning.Signs.pdf)

**Comment by MatthewJMcAllister** [comment]
Great comments, thank you, @amsignal!

**Comment by MatthewJMcAllister** [comment]
@amsignal, our team reviewed your letter. We appreciate the many excellent points raised in it and agree that there could be some ways to technically simplify this deployment. Part of the goal of using DSRC to complete the wireless connection to the advance warning sign is to test out the spectrum, consistency of communications, etc while DSRC-equipped vehicles remain low in volume. The sign can serve as a proxy for a vehicle at a fixed distance from the crossing. This Connected Pedestrian project helps us test those types of use cases in a controlled manner.

We will definitely be incorporating some of your feedback and comments in our final document. Thank you.
